---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20360.
--- DateTime: 2023/6/27 16:28
---
-- 参数：优惠券号和用户id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
--keys：stock 用户已下单的订单
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--判断库存，没有返回1
if(tonumber(redis.call('get',stockKey)) <=0) then
    return 1
end

--判断用户重复下单,返回2
if(redis.call('sismember',orderKey,userId) == 1) then
    return 2
end

--扣减库存，把userId存入已下单用户set
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
-- *表示消息id自动生成
redis.call('xadd','stream.orders','*','voucherId',voucherId,'userId',userId,'id',orderId)
return 0